apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  selector:
    app: conversao-temperatura
  ports: 
    - port: 80
      targetport: 8080
      nodePort: 30000
      protocol: TCP
  type: NodePort  
